site_name: Kotigo Studies
repo_url: https://github.com/jbcodeforce/kotigo-studies.git
nav:
  - Introduction: index.md
 
theme: 
  name: material
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences